FROM php:5.6-fpm-alpine
MAINTAINER bingo <bingov5@icloud.com>

RUN apk add --no-cache --virtual .build-deps \
         autoconf \
         build-base \
         bzip2-dev \
         gettext-dev \
         icu-dev \
         imagemagick-dev \
         imap-dev \
         libpng \
         libpng-dev \
         libjpeg-turbo \
         libjpeg-turbo-dev \
         libmemcached-dev \
         libssh2-dev \
         libtool \
         libltdl \
         libmcrypt-dev \
         libxml2-dev \
         libxslt-dev \
         openldap-dev \
         pcre-dev \
    && docker-php-ext-configure gd \ 
         --with-freetype-dir=/usr/include/ \
         --with-png-dir=/usr/include/ \
         --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install \
         iconv \
         bcmath \
         bz2 \
         calendar \
         dba \
         exif \
         gd \
         gettext \
         imap \
         intl \
         ldap \
         mcrypt \
         mysql \
         mysqli \
         opcache \
         pdo_mysql \
         shmop \
         soap \
         sockets \
         sysvmsg \
         sysvsem \
         sysvshm \
         wddx \
         xmlrpc \
         xsl \ 
         zip \
    && pecl install \
         igbinary \
         imagick \
         memcached-2.2.0 \
         msgpack-0.5.7 \
         redis \
    && echo "\n" | pecl install ssh2-0.13 \
    && docker-php-ext-enable --ini-name pecl.ini \
         igbinary \
         imagick \
         memcached \
         msgpack \
         redis \
         ssh2 \
    && apk del .build-deps