FROM php:5.6-fpm-alpine
MAINTAINER bingo <bingov5@icloud.com>

ENV TIMEZONE Asia/Shanghai
ENV PHPREDIS_VERSION 4.0.0RC1

RUN apk add --no-cache --virtual .php-ext-deps \
        curl \
        tzdata \
        freetype \
        libpng \
        libjpeg-turbo \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
    && curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mkdir -p /usr/src/php/ext \
    && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
    && ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
    && echo $TIMEZONE > /etc/timezone \
    && docker-php-ext-configure gd \
        --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-zlib-dir=/usr \
    && docker-php-ext-install \
        mbstring \
        opcache \
        pdo \
        pdo_mysql \
        mysql \
        mysqli \
        redis \
    && NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
    && docker-php-ext-install -j${NPROC} \ 
        gd \
        zip \
    && rm -rf /usr/src/php \
    && apk del .php-ext-deps